#!/bin/bash
cd "$(dirname "$0")"

function errorcheck() {
    if [ "$?" != 0 ] ; then 
        echo Press any key to continue...
        read -n 1
        exit $?
    fi
}

path=$( cd .. ; pwd )
name="${path##*/}"
if [ "$name"x = "com~apple~CloudDocs"x ]; then 
    buildPath="~/Playground.build"
else
    buildPath="../Playground.build"
fi

cmake -G Xcode -B $buildPath -S . -Wno-dev
errorcheck

cmake --open $buildPath
errorcheck

